version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_PASSWORD}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
